---
- hosts: appserver
  become: yes
  tasks:
    - name: get latest packages
      action: apt update_cache=yes
    - name: Install jq
      apt: name=jq update_cache=true state=latest
    - name: Install npm
      apt: name=npm state=installed update_cache=true state=latest
    - name: Install nodejs
      apt: name=nodejs update_cache=true state=latest
    - name: Create symlink for nodejs
      file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
    - name: Install git
      apt: name=git update_cache=true state=latest
    - name: install stress
      apt: pkg=stress state=installed
    - copy: src=./config.json dest=/root/config.json mode="u=rwx,g=rx,o=rx"
    - copy: src=./monitor/monitor_canary.sh dest=/root/monitor.sh mode=0777
    - name: "Install forever (to run server.js app)."
      npm: name=forever global=yes state=present
    - name: Clone the git repo
      git: repo=https://github.com/ankitkumar93/WebApp.git dest=/root/WebApp version=develop
    - name: Intall dependencies
      npm: path=/root/WebApp
    - name: "Check list of server.js apps running."
      command: forever list
      register: forever_list
      changed_when: false
    - name: "Start server.js app."
      command: /usr/local/bin/forever start /root/WebApp/server.js
      when: "forever_list.stdout.find('/root/WebApp/server.js') == -1"
    - name : "Move config.json to WebApp"
      command: cp /root/config.json /root/WebApp/config.json
    - name: Execute the monitoring script
      command: bash /root/monitor.sh
      async: 2
      poll: 0